CREATE TABLE todos (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    description VARCHAR(512) NOT NULL,
    completed TINYINT(3) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
